config/routes.rb
Janitor::Application.routes.draw do

  root 'dashboard#index'
  resources :turns, only: :index

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/duty.rb
class Duty < ActiveRecord::Base
  belongs_to :obliged, class_name: 'User'
  belongs_to :turn

  validates_presence_of :obliged, :turn, :appointed_at

  scope :between, ->(start_date, end_date) do
    where(created_at: start_date..end_date)
  end

  validate :appointed_to_friday

  private

  def appointed_to_friday
    unless appointed_at.friday?
      errors.add :appointed_at, 'Duty has to be appointed to Friday'
    end
  end
end

app/models/turn.rb
class Turn < ActiveRecord::Base
  has_many :turn_memberships, dependent: :destroy
  has_many :members, through: :turn_memberships, source: :user

  has_many :duties
end

app/models/turn_membership.rb
class TurnMembership < ActiveRecord::Base
  belongs_to :user
  belongs_to :turn

  validates_presence_of :user, :turn

  after_create :update_turn_members_changed_at
  after_destroy :update_turn_members_changed_at

  def update_turn_members_changed_at
    turn.update_attribute :members_changed_at, Date.today
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  has_many :turn_memberships, dependent: :destroy
  has_many :turns, through: :turn_memberships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authorize
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/turns_controller.rb
class TurnsController < ApplicationController
  def index
    @turns = current_user.turns.includes(duties: :obliged)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def beginning_of_this_week
    Time.now.beginning_of_week
  end
end

app/helpers/turns_helper.rb
module TurnsHelper
end

app/views/duties/_duty.html.slim
.duty
  = duty.obliged.email

app/views/layouts/_header.html.slim
#header
  .wrapper
    = link_to root_path do
      h1.logo Janitor
    .site-links
      - if signed_in?
        = current_user.email
        = link_to 'Sign out', sign_out_path, method: :delete
      - else
        = link_to 'Sign in', sign_in_path, class: 'btn blue'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Janitor
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  body
    = render 'layouts/header'
    .wrapper
      - if signed_in?
        .left-pane
          = render 'shared/site_links'
      == yield

app/views/shared/_site_links.html.slim
ul
  li= link_to 'Turns', turns_path

app/views/turns/_turn.html.slim
.turn
  = render DutiesBuilder.call turn, beginning_of_this_week, beginning_of_this_week + 4.weeks

app/views/turns/index.html.slim
= render @turns

app/views/users/_form.html.slim
.fields-container
  .field.width4
    = f.label :email
    = f.text_field :email, type: 'email'

  .field.width4
    = f.label :password
    = f.password_field :password

app/views/users/new.html.slim
.sign-up
  = form_for @user do |form|
    = render 'users/form', f: form

    .submit
      = form.submit

    .other-links
      = link_to t('.sign_in'), sign_in_path